plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.github.choreolooper'
    compileSdk 35

    defaultConfig {
        applicationId "com.github.choreolooper"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.02.07'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.drawerlayout
    implementation libs.webkit
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
